#pragma once

#define LISTOPAD_VERSION_MAJOR 0
#define LISTOPAD_VERSION_MINOR 1
#define LISTOPAD_VERSION_PATCH 0
#define LISTOPAD_VERSION_STRING "0.1.0"
#define LISTOPAD_VERSION_WSTRING L"0.1.0"
#define LISTOPAD_PRODUCT_NAME L"Listopad++"
#define LISTOPAD_EXE_NAME L"ListopadPP.exe"
#define LISTOPAD_PROTOCOL_VERSION 1u
