import { build } from 'esbuild';
import { readFile, writeFile, unlink } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, 'emmet.bundle.tmp.js');
const header = resolve(here, '../../assets/emmet_bundle.js.h');

await build({
  entryPoints: [resolve(here, 'entry.js')],
  outfile: output,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  legalComments: 'none'
});

const source = await readFile(output, 'utf8');
const chunks = [];
for (let offset = 0; offset < source.length; offset += 6000) {
  chunks.push(JSON.stringify(source.slice(offset, offset + 6000)));
}
const content = `#pragma once\n\n// Generated by tools/emmet/build.mjs from emmet@2.4.11.\ninline constexpr char kEmmetBundle[] =\n${chunks.map(chunk => `  ${chunk}`).join('\n')}\n;\n`;
await writeFile(header, content, 'utf8');
await unlink(output);
